apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql-container
        image: mysql:latest
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-root-password
                key: MYSQL_ROOT_PASSWORD
          - name: MYSQL_DATABASE
            value: wordpressdb
          - name: MYSQL_PASSWORD
            value: wordpresspass
          - name: MYSQL_USER
            value: wordpressUser
        ports:
          - containerPort: 3306
            name: mysql
        volumeMounts:
          - name:  mysql-data
            mountPath: /var/lib/mysql
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: my-pvc      

