apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress-container
        image: wordpress:latest
        env:
          - name: WORDPRESS_DB_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: wordpress-configmap
                key: WORDPRESS_DB_PASSWORD
          - name: WORDPRESS_DB_HOST
            valueFrom:
              configMapKeyRef:
                name: wordpress-configmap
                key: WORDPRESS_DB_HOST
          - name: WORDPRESS_DB_NAME
            valueFrom:
              configMapKeyRef:
                name: wordpress-configmap
                key: WORDPRESS_DB_NAME
          - name: WORDPRESS_DB_USER
            valueFrom:
              configMapKeyRef:
                name: wordpress-configmap
                key: WORDPRESS_DB_USER
        ports:
          - containerPort: 80
            name: wordpress

