apiVersion: v1
kind: Service
metadata:
  name: wordpress-nodeport
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080  # Optional: Kubernetes assigns a port if omitted
  selector:
    app: wordpress
