apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  namespace: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress-container
        image: wordpress:latest
        envFrom:
          - configMapRef:
              name: wordpress-config
          - secretRef:
              name: wordpress-secrets
        ports:
          - containerPort: 80
            name: wordpress
