apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment2
  namespace: frontend
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: wordpress
      version: v2
  template:
    metadata:
      labels:
        app: wordpress
        version: v2
    spec:
      containers:
      - name: wordpress-container
        image: wordpress:latest
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 15
        envFrom:
          - configMapRef:
              name: wordpress-config
          - secretRef:
              name: wordpress-secrets
        ports:
          - containerPort: 80
            name: wordpress
