apiVersion: v1
kind: Pod
metadata:
  name: 2-container-pod
  labels:
    name: 2-container-pod
spec:
  restartPolicy: Always
  containers:
    - name: wordpress
      image: wordpress:latest
      env:
        - name: WORDPRESS_DB_PASSWORD
          value: wordpresspass
        - name: WORDPRESS_DB_HOST
          value: 127.0.0.1
        - name: WORDPRESS_DB_NAME
          value: wordpressdb
        - name: WORDPRESS_DB_USER
          value: wordpressUser
      ports:
        - containerPort: 80
          name: wordpress
    - name: mysql
      image: mysql:latest
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_DATABASE
          value: wordpressdb
        - name: MYSQL_PASSWORD
          value: wordpresspass
        - name: MYSQL_USER
          value: wordpressUser
      ports:
        - containerPort: 3306
          name: mysql
